![PyData_logo](./static/pydata-logo-madrid-2016.png)

# Remove Before Flight
## Analyzing Flight Safety Data with Python

### Getting missing values of latitude and longitude with Google geocoding API

###### https://developers.google.com/maps/documentation/geocoding/intro?hl=es#geocoding

In [1]:
import pandas as pd
import numpy as np

%matplotlib notebook
import matplotlib.pyplot as plt

In [2]:
# Some configuration options:
pd.set_option('max_columns', 70)
pd.set_option('max_rows', 50)

In [3]:
# Read the missing locations
need_location = pd.read_csv('../data/need_location.csv', index_col='Unnamed: 0')
need_location.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4307 entries, 46 to 76878
Data columns (total 5 columns):
ev_city       4285 non-null object
ev_country    4170 non-null object
ev_state      2936 non-null object
latitude      0 non-null float64
longitude     1 non-null object
dtypes: float64(1), object(4)
memory usage: 201.9+ KB

In [4]:
need_location.tail()

               ev_city ev_country ev_state  latitude longitude
76812          Banbury         UK      NaN       NaN       NaN
76836  VERMILLION 255B        NaN       GM       NaN       NaN
76846           Kigali         RW      NaN       NaN       NaN
76850  JUNEAU                 USA       AK       NaN       NaN
76878          Cozumel         MX      NaN       NaN       NaN

In [5]:
from utils.geoloc import GoogleMapsClient

In [6]:
# read key from file:
# Your API key here https://developers.google.com/maps/documentation/geocoding/get-api-key
with open('./key.txt') as f:
    key = f.readline().rstrip('\n')

In [7]:
Session = GoogleMapsClient(key=key)

index = need_location.index
cities = need_location['ev_city'].values
states = need_location['ev_state'].values
countries = need_location['ev_country'].values

As the number of request is limited to 2500 requests per day, the dataframe needs to be splitted:

# Part 1: 0:1999
for ii in range(2000):
    location = Session.get_lat_lon_from_city_country(cities[ii], countries[ii], states[ii])
    if location != []:
        lat = location[0]
        lon = location[1]
        need_location.set_value(index[ii], 'latitude', lat)
        need_location.set_value(index[ii], 'longitude', lon)
        
need_location.iloc[0:2000].to_csv('../data/have_location_part1.csv')

In [8]:
need_location.iloc[0:2000]

                   ev_city ev_country ev_state  latitude longitude
46         NIGHTMUTE              USA       AK       NaN       NaN
50         UTICA                  USA       NY       NaN       NaN
56                 Toronto         CA      NaN       NaN       NaN
92                  Sydney         AS      NaN       NaN       NaN
116        GRAND JUNCTION         USA       CO       NaN       NaN
120        JUNEAU                 USA       AK       NaN       NaN
129        YUBA CITY              USA       CA       NaN       NaN
149                 Sidney        USA       MT       NaN       NaN
153      Lake in the Woods         CA       ON       NaN       NaN
163        KEMMERER               USA       WY       NaN       NaN
187                  Anaco         VE      NaN       NaN       NaN
257        UMIAT                  USA       AK       NaN       NaN
296            LA FORTUNA          PA      NaN       NaN       NaN
298                Bologna         IT      NaN       NaN       NaN
325                Madinah         SA      NaN       NaN       NaN
402        ATLANTA                USA       GA       NaN       NaN
435        HINCHINBROOK           USA       AK       NaN       NaN
442        SOUTH BEND             USA       IN       NaN       NaN
472             Arnos Vale         VC      NaN       NaN       NaN
485              Portreath         UK      NaN       NaN       NaN
489        AMERICAN RIVER         USA       AK       NaN       NaN
498                Raleigh        USA       NC       NaN       NaN
499        BENSON                 USA       AZ       NaN       NaN
524        VIEKODA BAY            USA       AK       NaN       NaN
530        JAGO RIVER             USA       AK       NaN       NaN
...                    ...        ...      ...       ...       ...
34633      DENVER                 USA       CO       NaN       NaN
34637      Puerta del Segu         SP      NaN       NaN       NaN
34655      FRIDAY HARBOR          USA       WA       NaN       NaN
34688           Santa Rosa         EC      NaN       NaN       NaN
34707      MCGRATH                USA       AK       NaN       NaN
34731      KANSAS CITY            USA       MO       NaN       NaN
34733      EUGENE ISLAND          NaN       GM       NaN       NaN
34765             Brussels         BE      NaN       NaN       NaN
34774      DUTCH HARBOR           USA       AK       NaN       NaN
34781               Denver        USA       CO       NaN       NaN
34810      PRUDHOE BAY            USA       AK       NaN       NaN
34818      DUFUR                  USA       OR       NaN       NaN
34841  Ballarat, Australia         AS      NaN       NaN       NaN
34861      WEST LAFAYETTE         USA       IN       NaN       NaN
34898      PUERTO PLATA            DR      NaN       NaN       NaN
34909          Mexico City         MX      NaN       NaN       NaN
34933      CESIS                   LG      NaN       NaN       NaN
34940      MEMPHIS                USA       TN       NaN       NaN
34947         Col de Menee         FR      NaN       NaN       NaN
35010      CHICAGO                USA       IL       NaN       NaN
35025      MUSKEGON               USA       MI       NaN       NaN
35031                Tokyo         JA      NaN       NaN       NaN
35096               TAIPEI         TW      NaN       NaN       NaN
35119      TALKEETNA              USA       AK       NaN       NaN
35153       RANCHO CORDOVA        USA       CA       NaN       NaN

[2000 rows x 5 columns]

In [9]:
need_location.iloc[2000:]

                ev_city ev_country ev_state  latitude longitude
35161             Miami        USA       FL       NaN       NaN
35187   CEDAR RAPIDS           USA       IA       NaN       NaN
35202   BURBANK                USA       CA       NaN       NaN
35212   BEDFORD PARK           USA       IL       NaN       NaN
35238   GARDNER                USA       KS       NaN       NaN
35240   FORT MYERS             USA       FL       NaN       NaN
35244   BETHEL                 USA       AK       NaN       NaN
35250     Naha, Okinawa         JA      NaN       NaN       NaN
35272          Godensee         AU      NaN       NaN       NaN
35275   MANILA                  RP      NaN       NaN       NaN
35283   CHARLESTON             USA       SC       NaN       NaN
35309      Candido Mota         BR      NaN       NaN       NaN
35310   QUITO                   EC      NaN       NaN       NaN
35365              BUGA         CO      NaN       NaN       NaN
35390   SAINT MARYS            USA       AK       NaN       NaN
35391   MONTEREY               USA       CA       NaN       NaN
35408   DAVENPORT              USA       IA       NaN       NaN
35481   JAMAICA                USA       NY       NaN       NaN
35487   Ciudad Victoria         MX      NaN       NaN       NaN
35517   JACKSONVILLE           USA       FL       NaN       NaN
35527   BIRMINGHAM             USA       AL       NaN       NaN
35538   QUINCY                 USA       CA       NaN       NaN
35544        El Marques         MX      NaN       NaN       NaN
35554       Ciudad Real         SP      NaN       NaN       NaN
35567   BULLHEAD CITY          USA       AZ       NaN       NaN
...                 ...        ...      ...       ...       ...
76475         Cochenour         CA      NaN       NaN       NaN
76493   BASEPOHL                GE      NaN       NaN       NaN
76498   OFFSHORE OIL           NaN       GM       NaN       NaN
76501   BERNARD                USA       IA       NaN       NaN
76503   NOME                   USA       AK       NaN       NaN
76505           BOLZANO         IT      NaN       NaN       NaN
76509       CELLE-ARLOH         GE      NaN       NaN       NaN
76540   TAMPA                  USA       FL       NaN       NaN
76576        Blackbushe         UK      NaN       NaN       NaN
76587   DARDANELLE             USA       CA       NaN       NaN
76593   DALHART                USA       TX       NaN       NaN
76596   HEBER CITY             USA       UT       NaN       NaN
76614   ST. IGNACE             USA       MI       NaN       NaN
76688   MIAMI                  USA       FL       NaN       NaN
76701   TULSA                  USA       OK       NaN       NaN
76712   MWANZA AIRPORT          TZ      NaN       NaN       NaN
76741      Barcelonette         FR      NaN       NaN       NaN
76750   LOS ANGELES            USA       CA       NaN       NaN
76776   GULF OF MEXICO         NaN       GM       NaN       NaN
76795  Mareeba Aerdrome         AS      NaN       NaN       NaN
76812           Banbury         UK      NaN       NaN       NaN
76836   VERMILLION 255B        NaN       GM       NaN       NaN
76846            Kigali         RW      NaN       NaN       NaN
76850   JUNEAU                 USA       AK       NaN       NaN
76878           Cozumel         MX      NaN       NaN       NaN

[2307 rows x 5 columns]

In [8]:
# Part 2: 2000:end
for ii in range(2000, len(need_location)):
    location = Session.get_lat_lon_from_city_country(cities[ii], countries[ii], states[ii])
    if location != []:
        lat = location[0]
        lon = location[1]
        need_location.set_value(index[ii], 'latitude', lat)
        need_location.set_value(index[ii], 'longitude', lon)
        

need_location.iloc[2000:].to_csv('../data/have_location_part2.csv')

wrong request: Kansai, JA
wrong request: Sucre, FN, BL
wrong request: Evora, FN, PO
wrong request: Googlong, NSW, AS
wrong request: Bosnia, BK
wrong request: TREASURE CAY   , BF
wrong request: W. CAMERON 617 , GM
wrong request: VERMILION 250  , GM
wrong request: TREASURE CAY   , BF
wrong request: DUNCAN TOWN    , BF
wrong request: EUCEMBUNE      , AS
wrong request: SHIP SHOAL 225 , GM
wrong request: TUCUTI , PM
wrong request: Makung Island, TW
wrong request: Rumbek, SU
wrong request: EC 270, GM, USA
wrong request: GULF-OF-MEXICO , GM
wrong request: GULF OF MEXICO , GM
wrong request: GULF OF MEXICO , GM
wrong request: STELLA MARIS   , BF
wrong request: Goma, CF
wrong request: SOTO CANO, HO
wrong request: PERDE BAY      , AK, USA
wrong request: RANCHO SANTA YN, MX
wrong request: Bourke , Australia, AS
wrong request: MIXCOLAJA      , GT
wrong request: Neuhausen ob Eck, GE
wrong request: Subic Bay, RP
wrong request: Main Pass 61A, GM, USA
wrong request: SHIP SHOAL 290K, GM
wrong request: Viru-Viru Int , BL
wrong request: Slieve Aughty Mountains, Co Galway, Ireland, EI
wrong request: Yao Airport, JA
wrong request: MIDDLE CAICOS  , TK
wrong request: EGWELL, GE
wrong request: BLUEFIELDS, NU
wrong request: KELLY RIVER BAR, AK, USA
wrong request: KAKO MINE STRIP, AK, USA
wrong request: CACKCHILA, GT
wrong request: Raharney, EI
wrong request: SNAEFELLSNES, IC
wrong request: PAVAS          , CS
wrong request: BRENON         , PM
wrong request: Minas Parapapoy, VE
wrong request: BRAZOS 542     , GM
wrong request: Benalla, AS
wrong request: Newgrange, EI
wrong request: SAN ANDROS     , BF
wrong request: British Virgin , VG
wrong request: WALKER CAY     , BF
wrong request: Tiers, Tasmania, AS
wrong request: SCHWENNIGEN, GE
wrong request: TIMBALIER ISLE , LA, USA
wrong request: WESTMAN ISLES  , IC
wrong request: 11MI. SO.OFTELL, CO, USA
wrong request: MARSH HARBOUR  , BF
wrong request: GULF-OF-MEXICO , GM
wrong request: SOUTH PELTO #1 , GM
wrong request: Subic Bay, RP
wrong request: PHILIPPINE ISLA, RP
wrong request: ST JOHN ANTIGUA, AC
wrong request: DEEP WATER CAY , BF
wrong request: Shimozishima , JA
wrong request: CAMARINES PROVI, RP
wrong request: EAST CAMERON   , GM
wrong request: Chanco, CI
wrong request: MISSING        , BF
wrong request: Leningradsky, RS
wrong request: 11NM EAST OF SI, AK, USA
wrong request: Gleiswile, GE
wrong request: Podnovye, RS
wrong request: Evora Aerodrome, PO
wrong request: HALLE-OPPIN    , GE
wrong request: S MARSH IS 7   , GM
wrong request: Lillo, UN, SP
wrong request: LITTLE WHALE   , BF
wrong request: GULF OF MEXICO , GM
wrong request: COPIAPO, CI
wrong request: JEREMIE        , HA
wrong request: Pista El Limon, EC
wrong request: CORNAKELLY     , EI
wrong request: SOUTH MARSH    , GM
wrong request: BERMUDA        , AO, BD
wrong request: Hrabove, UP
wrong request: 40 NM WNW SALMO, ID, USA
wrong request: Tanauan City, RP
wrong request: WALKER CAY     , BF
wrong request: Buttles Farm, Churchinford, UK, UK
wrong request: Tocumen, PM
wrong request: AMBERGRS, BH
wrong request: EAST CAMERON 71, GM
wrong request: GREEN CANYON172, GM
wrong request: WALKERS CAY    , BF
wrong request: Perm, RS
wrong request: SABA ISLAND    , NT
wrong request: ROCK SOUND     , BF
wrong request: SAN BLAS, PM
wrong request: Kastire, LG
wrong request: STANIEL CAY    , BF
wrong request: Teisendorf, GE
wrong request: BAYROUTH, GE
wrong request: SOLE LAKE      , AK, USA
wrong request: Heho, BM
wrong request: Villarrica, CI
wrong request: LISCOME BAY    , AK, USA
wrong request: 51 NM ESE YAKUT, AK, USA
wrong request: Foasi, PNG, ID
wrong request: GULF OF MEXICO , GM
wrong request: Sint Maartin -Juliana, FN, NT
wrong request: NORTH CAICOS   , TK
wrong request: BASEPOHL       , GE
wrong request: OFFSHORE OIL   , GM
wrong request: GULF OF MEXICO , GM

In [10]:
need_location.iloc[2000:]

                ev_city ev_country ev_state   latitude longitude
35161             Miami        USA       FL  25.761680  -80.1918
35187   CEDAR RAPIDS           USA       IA  41.977880  -91.6656
35202   BURBANK                USA       CA  34.180839  -118.309
35212   BEDFORD PARK           USA       IL  41.764172  -87.7813
35238   GARDNER                USA       KS  38.810841  -94.9272
35240   FORT MYERS             USA       FL  26.640628  -81.8723
35244   BETHEL                 USA       AK  60.792222  -161.756
35250     Naha, Okinawa         JA      NaN  26.195134    127.67
35272          Godensee         AU      NaN  48.143000   11.4249
35275   MANILA                  RP      NaN  14.599512   120.984
35283   CHARLESTON             USA       SC  32.776475  -79.9311
35309      Candido Mota         BR      NaN -22.746667   -50.388
35310   QUITO                   EC      NaN  -0.180653  -78.4678
35365              BUGA         CO      NaN   3.900508  -76.3022
35390   SAINT MARYS            USA       AK  62.053056  -163.166
35391   MONTEREY               USA       CA  36.600238  -121.895
35408   DAVENPORT              USA       IA  41.523644  -90.5776
35481   JAMAICA                USA       NY  40.702677   -73.789
35487   Ciudad Victoria         MX      NaN  23.736916  -99.1411
35517   JACKSONVILLE           USA       FL  30.332184  -81.6557
35527   BIRMINGHAM             USA       AL  33.520661  -86.8025
35538   QUINCY                 USA       CA  39.936836  -120.947
35544        El Marques         MX      NaN  20.583596  -100.373
35554       Ciudad Real         SP      NaN -23.632536  -46.7391
35567   BULLHEAD CITY          USA       AZ  35.135939  -114.529
...                 ...        ...      ...        ...       ...
76475         Cochenour         CA      NaN  51.071425  -93.8072
76493   BASEPOHL                GE      NaN        NaN       NaN
76498   OFFSHORE OIL           NaN       GM        NaN       NaN
76501   BERNARD                USA       IA  42.312230  -90.8318
76503   NOME                   USA       AK  64.501111  -165.406
76505           BOLZANO         IT      NaN  46.498295   11.3548
76509       CELLE-ARLOH         GE      NaN  52.617596   10.0629
76540   TAMPA                  USA       FL  27.950575  -82.4572
76576        Blackbushe         UK      NaN  51.877178  0.178349
76587   DARDANELLE             USA       CA  38.341023  -119.834
76593   DALHART                USA       TX  36.059477  -102.513
76596   HEBER CITY             USA       UT  40.507009  -111.413
76614   ST. IGNACE             USA       MI  45.875568  -84.7323
76688   MIAMI                  USA       FL  25.761680  -80.1918
76701   TULSA                  USA       OK  36.153982  -95.9928
76712   MWANZA AIRPORT          TZ      NaN  -2.441221   32.9232
76741      Barcelonette         FR      NaN  44.386300   6.65046
76750   LOS ANGELES            USA       CA  34.052234  -118.244
76776   GULF OF MEXICO         NaN       GM        NaN       NaN
76795  Mareeba Aerdrome         AS      NaN -16.991164   145.422
76812           Banbury         UK      NaN  52.062901  -1.33977
76836   VERMILLION 255B        NaN       GM  42.779442  -96.9292
76846            Kigali         RW      NaN  -1.970579   30.1044
76850   JUNEAU                 USA       AK  58.301944   -134.42
76878           Cozumel         MX      NaN  20.422984  -86.9223

[2307 rows x 5 columns]

In [11]:
need_location.iloc[2000:].to_csv('../data/have_location_part2.csv')

In [35]:
# Notebook style
from IPython.core.display import HTML
css_file = './static/style.css'
HTML(open(css_file, "r").read())